### ISSUE TITLE
[Bug] Wrong reference to the cart

### ISSUE THREAD

**Issue by Fifciu** [mollie/commercetools#165]
[There](https://github.com/mollie/commercetools/blob/develop/extension/src/requestHandlers/createOrder.ts#L261) is a wrong reference to the cart ID.

Instead of:
```js
const ctActions = await createCtActions(mollieCreatedOrder, ctPayment, cartByPayment.id);
```

There should be:
```js
const ctActions = await createCtActions(mollieCreatedOrder, ctPayment, cartByPayment.body.results[0].id);
```

**Comment by JoostMollie** [comment]
@denisand can you have a look at this?
