### ISSUE TITLE
Payment methods - missing enums mybank, voucher

### ISSUE THREAD

**Issue by lebradley** [mollie/commercetools#34]
# Payment Method - Missing enums

## Overview

Payment Method [enum](https://github.com/mollie/mollie-api-node/blob/fb6d001bbd944b9dcd257b3e9931e702407736f1/src/data/global.ts#L25) in mollie's node SDK does not contain `mybank` or `voucher` yet. 

These are valid for the `method` parameter on [create order](https://docs.mollie.com/reference/v2/orders-api/create-order)

This should be updated in either v3.6 or v4 (around January 2022) of the SDK. Until then, we will have a workaround in our code to allow those two extra types as well as the main `PaymentMethod`. 

## To do 

Once the SDK is updated, we need to : 
- update our code to use the new version
- remove the workaround
- close this issue

**Comment by denisand** [comment]
The way this works was changed in https://github.com/mollie/commercetools/commit/b704537adf7fb954a1bce0acdfa70c760e074a74#diff-c41a52d77641f2199a0eb4f06087777319fca43639f29c25d862c8204f18ffba
In the meantime SDK was updated and method now contains `mybank` as well.
